require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

RSpec/IndexedLet:
  AllowedIdentifiers:
    - p1
    - p2
