# config/buckler.yml

shared:
  base_url: <%= ENV["BUCKLER_BASE_URL"] %>
  user_agent: <%= ENV["BUCKLER_USER_AGENT"] %>
  email: <%= ENV["BUCKLER_EMAIL"] %>
  password: <%= ENV["BUCKLER_PASSWORD"] %>
