# config/buckler.yml

shared:
  base_url: <%= ENV.fetch("BUCKLER_BASE_URL") %>
  user_agent: <%= ENV.fetch("BUCKLER_USER_AGENT") %>
  email: <%= ENV.fetch("BUCKLER_EMAIL") %>
  password: <%= ENV.fetch("BUCKLER_PASSWORD") %>
