default: &default
  dispatchers:
    - polling_interval: <%= ENV.fetch("SOLID_QUEUE_DISPATCHERS_POOLING_INTERVAL", 1) %>
      batch_size: 500
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("SOLID_QUEUE_WORKERS_THREADS", 5) %>
      processes: <%= ENV.fetch("SOLID_QUEUE_WORKERS_PROCESSES", 1) %>
      polling_interval: <%= ENV.fetch("SOLID_QUEUE_WORKERS_POOLING_INTERVAL", 0.1) %>

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
